### ISSUE TITLE
netmesh process crash

### ISSUE THREAD

**Issue by sbezverk** [ligato/networkservicemesh#137]
There is a race condition due to the fact that crds are handled by two plugins instead of one. When crd plugin get `AfterInit` before the Handler plugin, then ObjectStore methods might not be ready and when it calls Handler's methods nil pointer exception happens.
```
time="2018-07-02 00:02:08.41343" level=info msg="LogCrdHandler.ObjectCreated: %!(EXTRA *reflect.rtype=*v1.NetworkService, *v1.NetworkService=&{{NetworkService networkservicemesh.io/v1} {gold-network  default /apis/networkservicemesh.io/v1/namespaces/default/networkservices/gold-network f5be5144-7d4d-11e8-98e0-5254004c4249 5601202 1 2018-07-01 16:44:02 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {name:\"gold-network\" namespace:\"default\" labels:<selector:<key:\"networkmesh.io/app\" value:\"gold-network\" > >  [metadata:<name:\"gold-ethernet\" > payload:\"ipv4\" ] {} [] 0} { }})" loc="handler/plugin_impl_handler.go(105)" logger=netmeshhandler
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x100a01b]
goroutine 94 [running]:
github.com/ligato/networkservicemesh/plugins/handler.(*Plugin).ObjectCreated(0xc4203613c0, 0x12c24a0, 0xc42057e000)
        /go/src/github.com/ligato/networkservicemesh/plugins/handler/plugin_impl_handler.go:106 +0x10b
github.com/ligato/networkservicemesh/plugins/crd.workforever.func1(0x141fae0, 0xc4203922e0, 0x11e7160, 0xc420596060, 0xc42022c220, 0x14, 0xc4203612a8, 0x141f1c0, 0xc4200ea2d0, 0xc42022c220, ...)
        /go/src/github.com/ligato/networkservicemesh/plugins/crd/crd_queue.go:124 +0x996
github.com/ligato/networkservicemesh/plugins/crd.workforever(0xc4203612a8, 0x141fae0, 0xc4203922e0, 0x141f1c0, 0xc4200ea2d0, 0xc420258840)
        /go/src/github.com/ligato/networkservicemesh/plugins/crd/crd_queue.go:134 +0xc5
created by github.com/ligato/networkservicemesh/plugins/crd.(*Plugin).AfterInit
        /go/src/github.com/ligato/networkservicemesh/plugins/crd/plugin_impl_crd.go:233 +0xb40
```
I do not see why would 2 plugins be required to deal with CRDs, single CRD plugin should be able to deal with all CRD related activities.

**Comment by mestery** [comment]
The original intent was to have plugins in the server but it appears we don’t need that so the handler can go away. I’ll propose a patch to remove it today once I merge #136.

**Comment by sbezverk** [comment]
@mestery imho we should not remove handler plugin, it is an excellent example of how to build plugins. There  should  be a reference in the documentation, for folks developing new plugins.
